### ISSUE TITLE
some suggestion for your wonderful work

### ISSUE THREAD

**Issue by normanlai** [RebliNk17/Discord-PokeSniper#6]
it would be good, if user can set a range of IV.   your work is excellent grabbing stuff from Discord, i would love to make it grab more pokemon in the range of 80-90 (eg Snorlax, Lapras)

can this app show the IV and CP of the creature caught, something like pokesniper2

to me the delay of 10 seconds still cause many API problems and flee. i find that 1 minute delay works best.  can this be user modified? 

perhaps the list of pokemon can be stored into a txt file and it can be queued and caught per minute.

the debug window showing all the IV of all the creatures is great.  it helps combine all the channels and filters, i use this now as my favorite manual snipe tool.

as promised.

**Comment by RebliNk17** [comment]
> it would be good, if user can set a range of IV. your work is excellent grabbing stuff from Discord, i would love to make it grab more pokemon in the range of 80-90 (eg Snorlax, Lapras)

Currently only 100% pokemons is allow,
maybe later (probably v2) i will expand it.

> can this app show the IV and CP of the creature caught, something like pokesniper2

In v1.5.0 CP is put next to the IV

> to me the delay of 10 seconds still cause many API problems and flee. i find that 1 minute delay works best. can this be user modified?

In v1.5.0 user can change waiting time.

> perhaps the list of pokemon can be stored into a txt file and it can be queued and caught per minute.

I don't understand what you mean.

> the debug window showing all the IV of all the creatures is great. it helps combine all the channels and filters, i use this now as my favorite manual snipe tool.

:-) Im glad it is helping you

**Comment by normanlai** [comment]
many software now, they may receive 10 monsters but they only catch the newest one.  they do not have a system to keep all the monsters for a certain period of time before flushing it. This feature is nice to have.

    perhaps the list of pokemon can be stored into a txt file and it can be queued and caught per minute.

I don't understand what you mean.
