### ISSUE TITLE
Catching

### ISSUE THREAD

**Issue by Ryanizleee** [RebliNk17/Discord-PokeSniper#8]
![653d2f883e2a69e30196ad6fc4deb66a](https://cloud.githubusercontent.com/assets/21989404/20310533/4355f844-ab87-11e6-9256-f69a035e7b5d.png)

No idea how it works, but it stays this way for like forever.
It's not sniping at all.

**Comment by Ryanizleee** [comment]
![115aa01260ec65500a6a248b797f834d](https://cloud.githubusercontent.com/assets/21989404/20379652/5bffda8e-acd8-11e6-8032-8190cfdb041b.png)

It does nothing, just Added to list.

**Comment by RebliNk17** [comment]
Http://discordps.com/downloads.php
V3.0.2 is out. No more pokesniper2 and Masterball. Lots of features were added...
